### ISSUE TITLE
ERROR::FREETYPE: Failed to load font

### ISSUE THREAD

**Issue by Basavaraj-PN** [maksmakuta/CProcessing#2]
Hi, I have installed freetype i'm still getting this error.
./sketch rendering black screen
I'm using Ubuntu 20.04

**Comment by sbond75** [comment]
I found the cause of this -- under [processing.h line 1183](https://github.com/maksmakuta/CProcessing/blob/dev/processing.h#L1183) there is a hardcoded path. I changed it on my machine. The default font is also initialized [here](https://github.com/maksmakuta/CProcessing/blob/dev/processing.h#L1297).

**Comment by maksmakuta** [comment]
Hello, I'm not have enougth time to develop this library. And yes font path is hardcoced. Need to specify default font depends on current system. Sorry for long answer...

**Comment by maksmakuta** [comment]
Fixed in ebfdcf8
